name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
          
      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build the package
        run: npm run build

      - name: Generate TypeScript code from protobuf definitions
        run: npm run generate

      - name: Install dependencies and publish
        run:  npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
